### PR TITLE
Support incremental builds

### LINKED ISSUE #8: Update NPM packages if newer version is available
We don't have a routine that checks for and installs any updates of the NPM packages.

### PR DESCRIPTION
**Pull request by annabarnes1138**
> I will merge this, but before I can publish a new version we have to implement a functionality to check if new plugins were added to the config.

I have addressed this with a couple of different changes
1. All of the available plugins packages will be installed by default, but will only be included if they are specified in the tailwind.config.js
2. I have implemented incremental builds so that msbuild will watch the tailwind.config.js for changes and rebuild the css if a change is detected. Otherwise it will skip it (this greatly improves build times)

> We need also to check for newer versions of the NPM packages, but because this is a general problem, I will open a new issue for this.

I have solved this by deleting the package-lock.json file when a `clean` is run. This triggers npm install to be re-run on the next build.

### CODE REVIEW

**Comment by BamButz** [comment]
Hey, thanks for your new contribution.

I've added a check to test if the build is still functional because your changes do break it.
Accidentally, I've committed with the wrong git credentials, so I had to rewrite the history to clean this up.
Can you rebase your branch and check if the action is running for this pull request?
If so and the checks are positive, I will review your changes asap to publish the new version. :)

**Comment by stecky** [comment]
OK @BamButz I think I finally have it working. Whew! That was tricky getting it to work in Windows!

**Comment by BamButz** [comment]
This looks good so far but to clarify your changes did remove the possibility to add custom plugins, and we could only use the official plugins I'm right?
I'm not certain if we should remove this functionality, as you can see here, there is a ton of [plugins](https://github.com/aniftyco/awesome-tailwindcss#plugins) that we wouldn't get to work without modifying the package.

In case I'm right, could you put that functionality back?

**Comment by stecky** [comment]
OK @BamButz. Done

**Comment by BamButz** [comment]
This is nearly perfect, but when I use this plugin in my config, it wouldn't trim the content behind the package name.

The resulting command is `npm install     "tailwindcss-elevation"(['responsive'])`

``` js
// tailwind.config.js
module.exports = {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [
    require('tailwindcss-elevation')(['responsive']),
  ],
}
```

I think we should reduce the logic to read the plugins to this because I assume that there is less of a lost require statement in the config than that there are complex configurations.

``` csharp
if (!File.Exists(ConfigFilePath))
    return true;

var cfgFileStr = File.ReadAllText(ConfigFilePath);

var matches = Regex.Matches(cfgFileStr, @"require\(['""](.*)['""]\)");
var plugins = new List<ITaskItem>(matches.Count);
foreach (Match match in matches)
    plugins.Add(new TaskItem(match.Groups[1].Value));

PluginsOut = plugins.ToArray();
```

Do you have any counterarguments?

**Comment by BamButz** [comment]
I truly agree with this. Sorry for the inconvenience.
So, I will merge this PR after you reverted the changes.

**Comment by stecky** [comment]
No worries. reverted.

**Review by BamButz — APPROVED** [review]
LGTM

**Pull request merged**
